/*
Copyright 2017 Turbine Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Automatically generated by MockGen. DO NOT EDIT!
// Source: fromenv.go

package flag

import (
	flag "flag"
	gomock "github.com/golang/mock/gomock"
)

// Mock of FromEnv interface
type MockFromEnv struct {
	ctrl     *gomock.Controller
	recorder *_MockFromEnvRecorder
}

// Recorder for MockFromEnv (not exported)
type _MockFromEnvRecorder struct {
	mock *MockFromEnv
}

func NewMockFromEnv(ctrl *gomock.Controller) *MockFromEnv {
	mock := &MockFromEnv{ctrl: ctrl}
	mock.recorder = &_MockFromEnvRecorder{mock}
	return mock
}

func (_m *MockFromEnv) EXPECT() *_MockFromEnvRecorder {
	return _m.recorder
}

func (_m *MockFromEnv) Prefix() string {
	ret := _m.ctrl.Call(_m, "Prefix")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockFromEnvRecorder) Prefix() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Prefix")
}

func (_m *MockFromEnv) Fill() {
	_m.ctrl.Call(_m, "Fill")
}

func (_mr *_MockFromEnvRecorder) Fill() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Fill")
}

func (_m *MockFromEnv) Filled() map[string]string {
	ret := _m.ctrl.Call(_m, "Filled")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

func (_mr *_MockFromEnvRecorder) Filled() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Filled")
}

func (_m *MockFromEnv) AllFlags() []*flag.Flag {
	ret := _m.ctrl.Call(_m, "AllFlags")
	ret0, _ := ret[0].([]*flag.Flag)
	return ret0
}

func (_mr *_MockFromEnvRecorder) AllFlags() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AllFlags")
}
