// Automatically generated by MockGen. DO NOT EDIT!
// Source: fromflags.go

package executor

import (
	gomock "github.com/golang/mock/gomock"
	log "log"
)

// Mock of FromFlags interface
type MockFromFlags struct {
	ctrl     *gomock.Controller
	recorder *_MockFromFlagsRecorder
}

// Recorder for MockFromFlags (not exported)
type _MockFromFlagsRecorder struct {
	mock *MockFromFlags
}

func NewMockFromFlags(ctrl *gomock.Controller) *MockFromFlags {
	mock := &MockFromFlags{ctrl: ctrl}
	mock.recorder = &_MockFromFlagsRecorder{mock}
	return mock
}

func (_m *MockFromFlags) EXPECT() *_MockFromFlagsRecorder {
	return _m.recorder
}

func (_m *MockFromFlags) Make(_param0 *log.Logger) Executor {
	ret := _m.ctrl.Call(_m, "Make", _param0)
	ret0, _ := ret[0].(Executor)
	return ret0
}

func (_mr *_MockFromFlagsRecorder) Make(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Make", arg0)
}
