// Automatically generated by MockGen. DO NOT EDIT!
// Source: diagnostics.go

package executor

import (
	gomock "github.com/golang/mock/gomock"
	time "time"
)

// Mock of DiagnosticsCallback interface
type MockDiagnosticsCallback struct {
	ctrl     *gomock.Controller
	recorder *_MockDiagnosticsCallbackRecorder
}

// Recorder for MockDiagnosticsCallback (not exported)
type _MockDiagnosticsCallbackRecorder struct {
	mock *MockDiagnosticsCallback
}

func NewMockDiagnosticsCallback(ctrl *gomock.Controller) *MockDiagnosticsCallback {
	mock := &MockDiagnosticsCallback{ctrl: ctrl}
	mock.recorder = &_MockDiagnosticsCallbackRecorder{mock}
	return mock
}

func (_m *MockDiagnosticsCallback) EXPECT() *_MockDiagnosticsCallbackRecorder {
	return _m.recorder
}

func (_m *MockDiagnosticsCallback) TaskStarted(_param0 int) {
	_m.ctrl.Call(_m, "TaskStarted", _param0)
}

func (_mr *_MockDiagnosticsCallbackRecorder) TaskStarted(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "TaskStarted", arg0)
}

func (_m *MockDiagnosticsCallback) TaskCompleted(_param0 AttemptResult, _param1 time.Duration) {
	_m.ctrl.Call(_m, "TaskCompleted", _param0, _param1)
}

func (_mr *_MockDiagnosticsCallbackRecorder) TaskCompleted(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "TaskCompleted", arg0, arg1)
}

func (_m *MockDiagnosticsCallback) AttemptStarted(_param0 time.Duration) {
	_m.ctrl.Call(_m, "AttemptStarted", _param0)
}

func (_mr *_MockDiagnosticsCallbackRecorder) AttemptStarted(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AttemptStarted", arg0)
}

func (_m *MockDiagnosticsCallback) AttemptCompleted(_param0 AttemptResult, _param1 time.Duration) {
	_m.ctrl.Call(_m, "AttemptCompleted", _param0, _param1)
}

func (_mr *_MockDiagnosticsCallbackRecorder) AttemptCompleted(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AttemptCompleted", arg0, arg1)
}

func (_m *MockDiagnosticsCallback) CallbackDuration(_param0 time.Duration) {
	_m.ctrl.Call(_m, "CallbackDuration", _param0)
}

func (_mr *_MockDiagnosticsCallbackRecorder) CallbackDuration(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CallbackDuration", arg0)
}
