/*
Copyright 2017 Turbine Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Automatically generated by MockGen. DO NOT EDIT!
// Source: timer.go

package time

import (
	gomock "github.com/golang/mock/gomock"
	time "time"
)

// Mock of Timer interface
type MockTimer struct {
	ctrl     *gomock.Controller
	recorder *_MockTimerRecorder
}

// Recorder for MockTimer (not exported)
type _MockTimerRecorder struct {
	mock *MockTimer
}

func NewMockTimer(ctrl *gomock.Controller) *MockTimer {
	mock := &MockTimer{ctrl: ctrl}
	mock.recorder = &_MockTimerRecorder{mock}
	return mock
}

func (_m *MockTimer) EXPECT() *_MockTimerRecorder {
	return _m.recorder
}

func (_m *MockTimer) C() <-chan time.Time {
	ret := _m.ctrl.Call(_m, "C")
	ret0, _ := ret[0].(<-chan time.Time)
	return ret0
}

func (_mr *_MockTimerRecorder) C() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "C")
}

func (_m *MockTimer) Reset(d time.Duration) bool {
	ret := _m.ctrl.Call(_m, "Reset", d)
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockTimerRecorder) Reset(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Reset", arg0)
}

func (_m *MockTimer) Stop() bool {
	ret := _m.ctrl.Call(_m, "Stop")
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockTimerRecorder) Stop() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Stop")
}
